export default [
  {
    ignores: ["dist/**", "node_modules/**", "public/pdfjs/**"],
  },
  {
    files: ["src/**/*.js", "vite.config.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        AbortController: "readonly",
        Blob: "readonly",
        CSS: "readonly",
        CustomEvent: "readonly",
        DOMParser: "readonly",
        FileReader: "readonly",
        FontFace: "readonly",
        FormData: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Highlight: "readonly",
        Image: "readonly",
        ImageData: "readonly",
        IntersectionObserver: "readonly",
        MutationObserver: "readonly",
        Node: "readonly",
        NodeFilter: "readonly",
        OffscreenCanvas: "readonly",
        Path2D: "readonly",
        Range: "readonly",
        ResizeObserver: "readonly",
        TextDecoder: "readonly",
        URL: "readonly",
        Worker: "readonly",
        atob: "readonly",
        btoa: "readonly",
        cancelAnimationFrame: "readonly",
        clearInterval: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        createImageBitmap: "readonly",
        crypto: "readonly",
        document: "readonly",
        fetch: "readonly",
        getComputedStyle: "readonly",
        indexedDB: "readonly",
        localStorage: "readonly",
        navigator: "readonly",
        performance: "readonly",
        queueMicrotask: "readonly",
        requestAnimationFrame: "readonly",
        setInterval: "readonly",
        setTimeout: "readonly",
        window: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
    },
  },
  {
    files: ["vite.config.js"],
    languageOptions: {
      globals: {
        process: "readonly",
      },
    },
  },
  {
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "off",
    },
  },
];
